default_context:
  project_name: 'API_Project'
  project_slug: 'api_project'
  domain_main: 'apiproject.com'
  domain_staging: 'staging.apiproject.com'
  docker_swarm_stack_name_main: 'api_project-com'
  docker_swarm_stack_name_staging: 'staging-api_project-com'
  secret_key: 'changethis'
  first_superuser: 'admin@apiproject.com'
  first_superuser_password: 'changethis'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.apiproject.com", "https://staging.apiproject.com", "https://apiproject.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@apiproject.com'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@apiproject.com'
  pgadmin_default_user_password: 'changethis'
  traefik_constraint_tag: 'apiproject.com'
  traefik_constraint_tag_staging: 'staging.apiproject.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:changethis'
  sentry_dsn: ''
  docker_image_prefix: 'api-project-'
  docker_image_backend: 'api-project-backend'
  docker_image_celeryworker: 'api-project-celeryworker'
  docker_image_frontend: 'api-project-frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
